devices:
  - port: /dev/ttyACM0          # (required) /dev/ttyACM0 (linux) or COM<X> (windows)
    radio_mode: 21              # (required)
    channel: 37                 # (required)
  - port: /dev/ttyACM2          # (required) /dev/ttyACM2 (linux) or COM<X> (windows)
    radio_mode: 21              # (required)
    channel: 38                 # (required)
  - port: /dev/ttyACM4          # (required) /dev/ttyACM4 (linux) or COM<X> (windows)
    radio_mode: 21              # (required)
    channel: 39                 # (required)
log:
  enabled: true                 # (optional - default) true | false
  path: ./                      # (optional - default) ./
  base_name: aceno              # (optional - default) aceno
  splitDevicesLog: true         # true | (optional - default) false
  resetPeriod: none             # (optional - default) none | hourly | daily | weekly | monthly
pipe:
  enabled: true                 # (optional - default) true | false
  name: test                    # (optional - default) aceno
  path: /tmp/                   # (optional - default) /tmp/ (linux) or \\.\pipe\ (windows)
                                # Pipes can be created wherever the user has write permissions on linux
                                # However, on Windows the pipe must be created at \\.\pipe\
  splitDevicesPipe: true        # true | (optional - default) false
                                # Pipes are created as <path>/<name>[-<id>] on Linux or \\.\pipe\<name>[-<id>] on Windows
                                # Pipes does not support the resetPeriod option