devices:
  - port: /dev/ttyACM0
    radio_mode: 20
    channel: 25
log:
  enabled: true
  path: ./
  base_name: aceno
  splitDevicesLog: false
  resetPeriod: daily
pipe:
  enabled: true
  name: aceno
  path: ./
  splitDevicesPipe: true
