# List of devices that you want to sniff. At least one device is required.
devices:
  - port: /dev/ttyACM0
    radio_mode: 20
    channel: 25
# Optional log options. Values below are the default ones.
# log:
#   enabled: true
#   path: ./
#   base_name: aceno
#   splitDevicesLog: false
#   resetPeriod: hourly # none | hourly | daily | weekly | monthly
# Optional pipe options. Values below are the default ones.
# On Windows the path name is ignored because the only path is \\.\pipe\
# With devices split, the pipe name is name_id.
# pipe:
#   enabled: true
#   name: aceno
#   path: /tmp/
#   splitDevicesPipe: false
# Optional time in seconds to execute the sniffer. When -1 runs indefinitely (default).
# duration: -1